//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloDotNET
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrmAppleEntities : DbContext
    {
        public CrmAppleEntities()
            : base("name=CrmAppleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Login> Logins { get; set; }
        public DbSet<Pengiriman> Pengirimen { get; set; }
        public DbSet<Produk> Produks { get; set; }
        public DbSet<Servi> Servis { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
