//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloDotNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pengiriman
    {
        public int Kode_Pengiriman { get; set; }
        public Nullable<System.DateTime> Tgl_kirim { get; set; }
        public Nullable<System.DateTime> Tgl_terima { get; set; }
    }
}
