//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloDotNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produk
    {
        public int Id_Produk { get; set; }
        public string Nama_produk { get; set; }
        public string Harga { get; set; }
        public string Spek { get; set; }
    }
}
